security:
    # Hashers de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Pas de sécurité pour les fichiers de développement comme les images, le profiler, etc.
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Route d'inscription ouverte à tous
        api_register:
            pattern: ^/api/register
            stateless: true
            security: false

        # Route de connexion ouverte à tous
        api_login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Routes protégées par JWT
        api:
            pattern: ^/api
            stateless: true
            jwt: ~  # Utilise le service JWT pour authentifier les requêtes

    # Contrôle d'accès
    access_control:
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Inscription sans authentification
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Connexion sans authentification
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }  # Autres routes API nécessitent un JWT valide

# Configuration pour les tests (optionnelle)
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4  # Valeur la plus basse pour bcrypt
                time_cost: 3  # Valeur la plus basse pour argon
                memory_cost: 10  # Valeur la plus basse pour argon
